### ISSUE TITLE
Show warning about 7-day deletion for Safari users

### ISSUE THREAD

**Issue by dstillman** [zotero/zoterobib#291]
https://forums.zotero.org/discussion/comment/428596/#Comment_428596

Both in the FAQ for everyone and maybe in the "Link to this version" section for Safari users specifically?

I can write the text, but we'll need an `isSafari` prop.

**Comment by tnajdek** [comment]
@dstillman I've added a warning in permalink section and a paragraph in FAQ. We have two entries in FAQ that could cover this, *How long is my bibliography stored?* and *Where is my bibliography stored?*, I've picked the latter for the warning but could go into either.

The warning will also appear for people using other browsers on iOS. I believe this is correct as, as far as I can tell, these browsers are still affected by ITP.

Please feel free to rephrase the warning and/or move the FAQ paragraph.
