### ISSUE TITLE
import existing bibliography to LocalStorage

### ISSUE THREAD

**Issue by rriemann** [zotero/zoterobib#302]
Dears,

I just learnt about this handy website. For my organisation, we look for a tool that offers us quick copy'n'paste for footnote-style references (Oscola style) of court cases and laws. We have a json and biblatex file with 60 pre-defined most-used references.

I thought I can just copy the CSL-JSON into the localstorage, but I see that the localstorage is not precisely using CSL-JSON standard. It would be nice to add thus an import tool for biblatex/CSL-JSON bibliographies.

Our long term solution is to use the Zotero integration in word processors, but there are some bugs that are much trickier to solve than the zoterobib web tool.

Example from our CSL-JSON:

```json
[
  {
    "URL": "http://data.europa.eu/eli/reg/2016/679/oj/eng",
    "accessed": {
      "date-parts": [
        [
          2018,
          1,
          7
        ]
      ]
    },
    "collection-title": "L",
    "container-title": "OJ",
    "genre": "regulation",
    "id": "gdpr",
    "issued": {
      "date-parts": [
        [
          2016,
          5,
          4
        ]
      ]
    },
    "keyword": "eu",
    "language": "en-US",
    "number": "2016/119",
    "page": "1",
    "title": "Regulation (EU) 2016/679 of the European Parliament and of the Council of 27 April 2016 on the Protection of Natural Persons with Regard to the Processing of Personal Data and on the Free Movement of Such Data, and Repealing Directive 95/46/EC (General Data Protection Regulation)",
    "title-short": "GDPR",
    "type": "legislation"
  },
  {
    "URL": "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:62014CA0201",
    "id": "ecj:c-201/14",
    "issued": {
      "date-parts": [
        [
          2015,
          10,
          1
        ]
      ]
    },
    "keyword": "eu",
    "note": "Judgment of the Court (Third Chamber)",
    "number": "C-201/14",
    "publisher": "ECJ",
    "title": "Smaranda bara and others v președintele casei naționale de asigurări de sănătate, casa naţională de asigurări de sănătate, agenţia naţională de administrare fiscală",
    "type": "legal_case"
  }
]
```

**Comment by tnajdek** [comment]
Zotero does not use GitHub Issues for feature requests, in future please post to the [Zotero Forums](https://forums.zotero.org).

You should be able to paste CSL-JSON or Biblatex (and many other formats that Zotero itself understands) into the main input (the one that says `Enter a URL, ISBN, DOI, PMID, arXiv ID, or title`). This should result in a dialog which allows you to pick any number of pasted citations to include in your bibliography, which you can then use to generated references as needed.

I hope this helps, if you have any other questions, please use Zotero forums for further discussion.
