### ISSUE TITLE
Feature Request: Import list of references

### ISSUE THREAD

**Issue by deedeeharris** [zotero/zoterobib#305]
Feature Request:

Title: Allow Batch Import of References and Bulk Conversion to Different Citation Formats

Description:
Currently, zbib.org offers a convenient platform for managing references and generating citations. To enhance user experience and efficiency, I propose the implementation of a feature that enables users to import a list of references in bulk and subsequently convert the entire list to a different citation format.

Feature Details:
1. **Batch Import Functionality**: Introduce an option for users to upload a file or paste a list of references in a specified format for bulk import.
   
2. **Bulk Conversion**: After importing the references, provide users with the ability to select a desired citation format for the entire list.
   
3. **User-Friendly Interface**: Ensure a seamless and intuitive user interface that guides users through the import and conversion process.

4. **Error Handling**: Implement error-checking mechanisms to notify users of any issues during the import or conversion process.

5. **Feedback Mechanism**: Allow users to provide feedback on the imported references and the converted citations for continuous improvement.

This feature would significantly streamline the citation management process for users, saving time and effort when working with large sets of references. Your consideration of this enhancement would be greatly appreciated by the zbib.org community.

Thank you for your attention to this feature request.

**Comment by tnajdek** [comment]
We don't generally use Github issues for feature requests, please see: https://github.com/zotero/zotero/blob/main/CONTRIBUTING.md

Partially this is already available: It's possible to paste references in any format recognized by Zotero and this performs batch import (however the UI is currently quite cumbersome, but that will be fixed - see #303). However, in general, I think this request might be outside of the scope for Zoterobib. I believe you can perform all these tasks already with Zotero.

I'm closing this issue, if you'd like to discuss more, please use Zotero forums.
